"use strict";
/* global Asset */

/* This JS file was generated by NoxioAssetConverter */
Asset.prototype.material = {};
Asset.prototype.material.multi = {};
Asset.prototype.material.multi.hit = {};
Asset.prototype.material.character = {};
Asset.prototype.material.character.cargo = {};
Asset.prototype.material.character.cargo.decal = {};
Asset.prototype.material.character.cargo.ui = {};
Asset.prototype.material.character.cargo.effect = {};
Asset.prototype.material.character.block = {};
Asset.prototype.material.character.block.ui = {};
Asset.prototype.material.character.block.effect = {};
Asset.prototype.material.character.cube = {};
Asset.prototype.material.character.cube.ui = {};
Asset.prototype.material.character.poly = {};
Asset.prototype.material.character.poly.decal = {};
Asset.prototype.material.character.poly.ui = {};
Asset.prototype.material.character.voxel = {};
Asset.prototype.material.character.voxel.ui = {};
Asset.prototype.material.character.voxel.effect = {};
Asset.prototype.material.character.quad = {};
Asset.prototype.material.character.quad.ui = {};
Asset.prototype.material.character.quad.effect = {};
Asset.prototype.material.character.box = {};
Asset.prototype.material.character.box.ui = {};
Asset.prototype.material.character.box.effect = {};
Asset.prototype.material.character.xob = {};
Asset.prototype.material.character.xob.decal = {};
Asset.prototype.material.character.xob.ui = {};
Asset.prototype.material.character.crate = {};
Asset.prototype.material.character.crate.ui = {};
Asset.prototype.material.character.crate.effect = {};
Asset.prototype.material.character.inferno = {};
Asset.prototype.material.character.inferno.ui = {};
Asset.prototype.material.character.generic = {};
Asset.prototype.material.character.generic.decal = {};
Asset.prototype.material.character.generic.ui = {};
Asset.prototype.material.character.generic.effect = {};
Asset.prototype.material.sky = {};
Asset.prototype.material.sky.vapor = {};
Asset.prototype.material.sky.gold = {};
Asset.prototype.material.sky.final = {};
Asset.prototype.material.ui = {};
Asset.prototype.material.ui.tutorial = {};
Asset.prototype.material.map = {};
Asset.prototype.material.map.copper = {};
Asset.prototype.material.map.gold = {};
Asset.prototype.material.map.iron = {};
Asset.prototype.material.map.tin = {};
Asset.prototype.material.object = {};
Asset.prototype.material.object.bomb = {};
Asset.prototype.material.object.zone = {};
Asset.prototype.material.object.flag = {};
Asset.prototype.material.object.hill = {};
Asset.prototype.material.object.generic = {};
Asset.prototype.material.object.generic.decal = {};

/* Source File: default.mat */
Asset.prototype.material.multi.default = {
  name: "multi.default",
  shader: "default",
  shadow: "true",
  bloom: "false",
  texture0: "multi/default",
  texture1: "multi/normal",
};

/* Source File: debug.mat */
Asset.prototype.material.multi.debug = {
  name: "multi.debug",
  shader: "debug",
  shadow: "false",
  bloom: "false",
};

/* Source File: post_msaa_bloom.mat */
Asset.prototype.material.multi.post_msaa_bloom = {
  name: "multi.post_msaa_bloom",
  shader: "post_msaa_bloom",
  shadow: "false",
  bloom: "false",
};

/* Source File: shadowmask.mat */
Asset.prototype.material.multi.shadowmask = {
  name: "multi.shadowmask",
  shader: "shadowmask",
  shadow: "true",
  bloom: "false",
};

/* Source File: zap.mat */
Asset.prototype.material.multi.hit.zap = {
  name: "multi.hit.zap",
  shader: "particlesprite",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/zap",
};

/* Source File: sparkRB.mat */
Asset.prototype.material.multi.hit.sparkRB = {
  name: "multi.hit.sparkRB",
  shader: "particlemodelRB",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/spark",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: critflare.mat */
Asset.prototype.material.multi.hit.critflare = {
  name: "multi.hit.critflare",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/critflare",
};

/* Source File: slashRB.mat */
Asset.prototype.material.multi.hit.slashRB = {
  name: "multi.hit.slashRB",
  shader: "particlespriteRB",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/slash",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: burnRB.mat */
Asset.prototype.material.multi.hit.burnRB = {
  name: "multi.hit.burnRB",
  shader: "particlespriteRB",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/flame",
  texture1: "multi/red_mid",
  texture2: "multi/white",
};

/* Source File: line.mat */
Asset.prototype.material.multi.hit.line = {
  name: "multi.hit.line",
  shader: "particlemodel",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/line",
};

/* Source File: zapRB.mat */
Asset.prototype.material.multi.hit.zapRB = {
  name: "multi.hit.zapRB",
  shader: "particlespriteRB",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/zap",
  texture1: "multi/red_low",
  texture2: "multi/white",
};

/* Source File: slash.mat */
Asset.prototype.material.multi.hit.slash = {
  name: "multi.hit.slash",
  shader: "particlesprite",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/slash",
};

/* Source File: smoke.mat */
Asset.prototype.material.multi.hit.smoke = {
  name: "multi.hit.smoke",
  shader: "particlesprite",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/smoke",
};

/* Source File: lineRB.mat */
Asset.prototype.material.multi.hit.lineRB = {
  name: "multi.hit.lineRB",
  shader: "particlemodelRB",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/line",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: burn.mat */
Asset.prototype.material.multi.hit.burn = {
  name: "multi.hit.burn",
  shader: "particlesprite",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/flame",
};

/* Source File: critspark.mat */
Asset.prototype.material.multi.hit.critspark = {
  name: "multi.hit.critspark",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/critspark",
};

/* Source File: spark.mat */
Asset.prototype.material.multi.hit.spark = {
  name: "multi.hit.spark",
  shader: "particlemodel",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/spark",
};

/* Source File: post_msaa.mat */
Asset.prototype.material.multi.post_msaa = {
  name: "multi.post_msaa",
  shader: "post_msaa",
  shadow: "false",
  bloom: "false",
};

/* Source File: shadow.mat */
Asset.prototype.material.multi.shadow = {
  name: "multi.shadow",
  shader: "shadow",
  shadow: "true",
  bloom: "false",
};

/* Source File: gold.mat */
Asset.prototype.material.character.cargo.gold = {
  name: "character.cargo.gold",
  shader: "playershiny",
  shadow: "true",
  bloom: "false",
  texture0: "character/cargo/cargo",
  texture1: "character/cargo/cargo_normal",
  texture2: "character/cargo/gold",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: delta.mat */
Asset.prototype.material.character.cargo.delta = {
  name: "character.cargo.delta",
  shader: "playerdelta",
  shadow: "true",
  bloom: "false",
  texture0: "character/cargo/cargo",
  texture1: "character/cargo/cargo_normal",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: indicator.mat */
Asset.prototype.material.character.cargo.decal.indicator = {
  name: "character.cargo.decal.indicator",
  shader: "decal_glow",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/decal/indicator",
};

/* Source File: reverse.mat */
Asset.prototype.material.character.cargo.reverse = {
  name: "character.cargo.reverse",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/cargo/reverse",
  texture1: "character/cargo/cargo_normal",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.cargo.ui.iconsmall = {
  name: "character.cargo.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/ui/icon_sm",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.cargo.ui.iconlarge = {
  name: "character.cargo.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/ui/icon_lg",
};

/* Source File: cargo.mat */
Asset.prototype.material.character.cargo.cargo = {
  name: "character.cargo.cargo",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/cargo/cargo",
  texture1: "character/cargo/cargo_normal",
};

/* Source File: shockwaveRB.mat */
Asset.prototype.material.character.cargo.effect.shockwaveRB = {
  name: "character.cargo.effect.shockwaveRB",
  shader: "effectRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/effect/shockwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: flashRB.mat */
Asset.prototype.material.character.cargo.effect.flashRB = {
  name: "character.cargo.effect.flashRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/effect/flash",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: blastRB.mat */
Asset.prototype.material.character.cargo.effect.blastRB = {
  name: "character.cargo.effect.blastRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/effect/shockwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: shockwave.mat */
Asset.prototype.material.character.cargo.effect.shockwave = {
  name: "character.cargo.effect.shockwave",
  shader: "effect2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/effect/shockwave",
};

/* Source File: ray.mat */
Asset.prototype.material.character.cargo.effect.ray = {
  name: "character.cargo.effect.ray",
  shader: "particlemodel",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/effect/ray",
};

/* Source File: blast.mat */
Asset.prototype.material.character.cargo.effect.blast = {
  name: "character.cargo.effect.blast",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/effect/shockwave",
};

/* Source File: flash.mat */
Asset.prototype.material.character.cargo.effect.flash = {
  name: "character.cargo.effect.flash",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/effect/flash",
};

/* Source File: rayRB.mat */
Asset.prototype.material.character.cargo.effect.rayRB = {
  name: "character.cargo.effect.rayRB",
  shader: "particlemodelRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/cargo/effect/ray",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: gold.mat */
Asset.prototype.material.character.block.gold = {
  name: "character.block.gold",
  shader: "playershiny",
  shadow: "true",
  bloom: "false",
  texture0: "character/block/block",
  texture1: "character/block/block_normal",
  texture2: "character/block/gold",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: delta.mat */
Asset.prototype.material.character.block.delta = {
  name: "character.block.delta",
  shader: "playerdelta",
  shadow: "true",
  bloom: "false",
  texture0: "character/block/block",
  texture1: "character/block/block_normal",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: reverse.mat */
Asset.prototype.material.character.block.reverse = {
  name: "character.block.reverse",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/block/reverse",
  texture1: "character/block/block_normal",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.block.ui.iconsmall = {
  name: "character.block.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/ui/icon_sm",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.block.ui.iconlarge = {
  name: "character.block.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/ui/icon_lg",
};

/* Source File: block.mat */
Asset.prototype.material.character.block.block = {
  name: "character.block.block",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/block/block",
  texture1: "character/block/block_normal",
};

/* Source File: sleepRB.mat */
Asset.prototype.material.character.block.effect.sleepRB = {
  name: "character.block.effect.sleepRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/z",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: dashRB.mat */
Asset.prototype.material.character.block.effect.dashRB = {
  name: "character.block.effect.dashRB",
  shader: "particlespriteRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/dash",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: shockwaveRB.mat */
Asset.prototype.material.character.block.effect.shockwaveRB = {
  name: "character.block.effect.shockwaveRB",
  shader: "effectRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/shockwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: sleep.mat */
Asset.prototype.material.character.block.effect.sleep = {
  name: "character.block.effect.sleep",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/z",
};

/* Source File: hitwave.mat */
Asset.prototype.material.character.block.effect.hitwave = {
  name: "character.block.effect.hitwave",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/hitwave",
};

/* Source File: dash.mat */
Asset.prototype.material.character.block.effect.dash = {
  name: "character.block.effect.dash",
  shader: "particlesprite",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/dash",
};

/* Source File: line.mat */
Asset.prototype.material.character.block.effect.line = {
  name: "character.block.effect.line",
  shader: "particlemodel",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/line",
};

/* Source File: shockwave.mat */
Asset.prototype.material.character.block.effect.shockwave = {
  name: "character.block.effect.shockwave",
  shader: "effect",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/shockwave",
};

/* Source File: smokeRB.mat */
Asset.prototype.material.character.block.effect.smokeRB = {
  name: "character.block.effect.smokeRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/smoke",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: restwaveRB.mat */
Asset.prototype.material.character.block.effect.restwaveRB = {
  name: "character.block.effect.restwaveRB",
  shader: "effectRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/hitwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: smoke.mat */
Asset.prototype.material.character.block.effect.smoke = {
  name: "character.block.effect.smoke",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/smoke",
};

/* Source File: hitRB.mat */
Asset.prototype.material.character.block.effect.hitRB = {
  name: "character.block.effect.hitRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/cross",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: hitwaveRB.mat */
Asset.prototype.material.character.block.effect.hitwaveRB = {
  name: "character.block.effect.hitwaveRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/hitwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: hit.mat */
Asset.prototype.material.character.block.effect.hit = {
  name: "character.block.effect.hit",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/cross",
};

/* Source File: lineRB.mat */
Asset.prototype.material.character.block.effect.lineRB = {
  name: "character.block.effect.lineRB",
  shader: "particlemodelRB",
  shadow: "false",
  bloom: "false",
  texture0: "multi/hit/line",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: restwave.mat */
Asset.prototype.material.character.block.effect.restwave = {
  name: "character.block.effect.restwave",
  shader: "effect",
  shadow: "false",
  bloom: "false",
  texture0: "character/block/effect/hitwave",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.cube.ui.iconsmall = {
  name: "character.cube.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/cube/ui/icon_sm",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.cube.ui.iconlarge = {
  name: "character.cube.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/cube/ui/icon_lg",
};

/* Source File: cube.mat */
Asset.prototype.material.character.cube.cube = {
  name: "character.cube.cube",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/cube/cube",
  texture1: "character/cube/cube_normal",
};

/* Source File: targetcircle.mat */
Asset.prototype.material.character.poly.decal.targetcircle = {
  name: "character.poly.decal.targetcircle",
  shader: "decal_glow_noneg",
  shadow: "false",
  bloom: "false",
  texture0: "character/poly/decal/targetdecal",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.poly.ui.iconsmall = {
  name: "character.poly.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/poly/ui/icon_sm",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.poly.ui.iconlarge = {
  name: "character.poly.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/poly/ui/icon_lg",
};

/* Source File: voxel.mat */
Asset.prototype.material.character.voxel.voxel = {
  name: "character.voxel.voxel",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/voxel/voxel",
  texture1: "character/voxel/voxel_normal",
};

/* Source File: gold.mat */
Asset.prototype.material.character.voxel.gold = {
  name: "character.voxel.gold",
  shader: "playershiny",
  shadow: "true",
  bloom: "false",
  texture0: "character/voxel/voxel",
  texture1: "character/voxel/voxel_normal",
  texture2: "character/voxel/gold",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: delta.mat */
Asset.prototype.material.character.voxel.delta = {
  name: "character.voxel.delta",
  shader: "playerdelta",
  shadow: "true",
  bloom: "false",
  texture0: "character/voxel/voxel",
  texture1: "character/voxel/voxel_normal",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: reverse.mat */
Asset.prototype.material.character.voxel.reverse = {
  name: "character.voxel.reverse",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/voxel/reverse",
  texture1: "character/voxel/voxel_normal",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.voxel.ui.iconsmall = {
  name: "character.voxel.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/ui/icon_sm",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.voxel.ui.iconlarge = {
  name: "character.voxel.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/ui/icon_lg",
};

/* Source File: shockwaveRB.mat */
Asset.prototype.material.character.voxel.effect.shockwaveRB = {
  name: "character.voxel.effect.shockwaveRB",
  shader: "effectRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/effect/shockwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: flashRB.mat */
Asset.prototype.material.character.voxel.effect.flashRB = {
  name: "character.voxel.effect.flashRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/effect/flash",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: line.mat */
Asset.prototype.material.character.voxel.effect.line = {
  name: "character.voxel.effect.line",
  shader: "particlemodel",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/effect/line",
};

/* Source File: shockwave.mat */
Asset.prototype.material.character.voxel.effect.shockwave = {
  name: "character.voxel.effect.shockwave",
  shader: "effect",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/effect/shockwave",
};

/* Source File: markRB.mat */
Asset.prototype.material.character.voxel.effect.markRB = {
  name: "character.voxel.effect.markRB",
  shader: "effectRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/effect/mark",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: markwave.mat */
Asset.prototype.material.character.voxel.effect.markwave = {
  name: "character.voxel.effect.markwave",
  shader: "effect2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/effect/markwave",
};

/* Source File: markwaveRB.mat */
Asset.prototype.material.character.voxel.effect.markwaveRB = {
  name: "character.voxel.effect.markwaveRB",
  shader: "effectRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/effect/markwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: lineRB.mat */
Asset.prototype.material.character.voxel.effect.lineRB = {
  name: "character.voxel.effect.lineRB",
  shader: "particlemodelRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/effect/line",
  texture1: "multi/red_high",
  texture2: "multi/white",
};

/* Source File: mark.mat */
Asset.prototype.material.character.voxel.effect.mark = {
  name: "character.voxel.effect.mark",
  shader: "effect",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/effect/mark",
};

/* Source File: flash.mat */
Asset.prototype.material.character.voxel.effect.flash = {
  name: "character.voxel.effect.flash",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "character/voxel/effect/flash",
};

/* Source File: gold.mat */
Asset.prototype.material.character.quad.gold = {
  name: "character.quad.gold",
  shader: "playershiny",
  shadow: "true",
  bloom: "false",
  texture0: "character/quad/quad",
  texture1: "character/quad/quad_normal",
  texture2: "character/quad/gold",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: delta.mat */
Asset.prototype.material.character.quad.delta = {
  name: "character.quad.delta",
  shader: "playerdelta",
  shadow: "true",
  bloom: "false",
  texture0: "character/quad/quad",
  texture1: "character/quad/quad_normal",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: reverse.mat */
Asset.prototype.material.character.quad.reverse = {
  name: "character.quad.reverse",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/quad/reverse",
  texture1: "character/quad/quad_normal",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.quad.ui.iconsmall = {
  name: "character.quad.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/quad/ui/icon_sm",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.quad.ui.iconlarge = {
  name: "character.quad.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/quad/ui/icon_lg",
};

/* Source File: quad.mat */
Asset.prototype.material.character.quad.quad = {
  name: "character.quad.quad",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/quad/quad",
  texture1: "character/quad/quad_normal",
};

/* Source File: shockwaveGroundRB.mat */
Asset.prototype.material.character.quad.effect.shockwaveGroundRB = {
  name: "character.quad.effect.shockwaveGroundRB",
  shader: "effectRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/quad/effect/shockwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: shockwaveRB.mat */
Asset.prototype.material.character.quad.effect.shockwaveRB = {
  name: "character.quad.effect.shockwaveRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/quad/effect/shockwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: slashRB.mat */
Asset.prototype.material.character.quad.effect.slashRB = {
  name: "character.quad.effect.slashRB",
  shader: "effect_slashRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/quad/effect/slashmask",
  texture1: "character/quad/effect/slashgrad",
  texture2: "multi/rainbow_low",
  texture3: "multi/rainbow_high",
};

/* Source File: riposteRB.mat */
Asset.prototype.material.character.quad.effect.riposteRB = {
  name: "character.quad.effect.riposteRB",
  shader: "effect_slashRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/quad/effect/ripostemask",
  texture1: "character/quad/effect/slashgrad",
  texture2: "multi/rainbow_low",
  texture3: "multi/rainbow_high",
};

/* Source File: shockwave.mat */
Asset.prototype.material.character.quad.effect.shockwave = {
  name: "character.quad.effect.shockwave",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/quad/effect/shockwave",
};

/* Source File: slash.mat */
Asset.prototype.material.character.quad.effect.slash = {
  name: "character.quad.effect.slash",
  shader: "effect_slash",
  shadow: "false",
  bloom: "false",
  texture0: "character/quad/effect/slashmask",
  texture1: "character/quad/effect/slashgrad",
};

/* Source File: shockwaveGround.mat */
Asset.prototype.material.character.quad.effect.shockwaveGround = {
  name: "character.quad.effect.shockwaveGround",
  shader: "effect2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/quad/effect/shockwave",
};

/* Source File: riposte.mat */
Asset.prototype.material.character.quad.effect.riposte = {
  name: "character.quad.effect.riposte",
  shader: "effect_slash",
  shadow: "false",
  bloom: "false",
  texture0: "character/quad/effect/ripostemask",
  texture1: "character/quad/effect/slashgrad",
};

/* Source File: gold.mat */
Asset.prototype.material.character.box.gold = {
  name: "character.box.gold",
  shader: "playershiny",
  shadow: "true",
  bloom: "false",
  texture0: "character/box/box",
  texture1: "character/box/box_normal",
  texture2: "character/box/gold",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: delta.mat */
Asset.prototype.material.character.box.delta = {
  name: "character.box.delta",
  shader: "playerdelta",
  shadow: "true",
  bloom: "false",
  texture0: "character/box/box",
  texture1: "character/box/box_normal",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: reverse.mat */
Asset.prototype.material.character.box.reverse = {
  name: "character.box.reverse",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/box/reverse",
  texture1: "character/box/box_normal",
};

/* Source File: box.mat */
Asset.prototype.material.character.box.box = {
  name: "character.box.box",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/box/box",
  texture1: "character/box/box_normal",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.box.ui.iconsmall = {
  name: "character.box.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/ui/icon_sm",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.box.ui.iconlarge = {
  name: "character.box.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/ui/icon_lg",
};

/* Source File: hat.mat */
Asset.prototype.material.character.box.hat = {
  name: "character.box.hat",
  shader: "default",
  shadow: "true",
  bloom: "false",
  texture0: "character/box/hat",
  texture1: "multi/normal",
};

/* Source File: hitA.mat */
Asset.prototype.material.character.box.effect.hitA = {
  name: "character.box.effect.hitA",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/hit_a",
};

/* Source File: initial.mat */
Asset.prototype.material.character.box.effect.initial = {
  name: "character.box.effect.initial",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/blip_init",
};

/* Source File: sparkRB.mat */
Asset.prototype.material.character.box.effect.sparkRB = {
  name: "character.box.effect.sparkRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/spark",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: shockwaveRB.mat */
Asset.prototype.material.character.box.effect.shockwaveRB = {
  name: "character.box.effect.shockwaveRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/shockwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: blipDelta.mat */
Asset.prototype.material.character.box.effect.blipDelta = {
  name: "character.box.effect.blipDelta",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/blip_delta",
};

/* Source File: flashRB.mat */
Asset.prototype.material.character.box.effect.flashRB = {
  name: "character.box.effect.flashRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/flash",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: blipRB.mat */
Asset.prototype.material.character.box.effect.blipRB = {
  name: "character.box.effect.blipRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/blip",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: speedline.mat */
Asset.prototype.material.character.box.effect.speedline = {
  name: "character.box.effect.speedline",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/speedline",
};

/* Source File: hitB.mat */
Asset.prototype.material.character.box.effect.hitB = {
  name: "character.box.effect.hitB",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/hit_b",
};

/* Source File: shockwave.mat */
Asset.prototype.material.character.box.effect.shockwave = {
  name: "character.box.effect.shockwave",
  shader: "effect2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/shockwave",
};

/* Source File: blip.mat */
Asset.prototype.material.character.box.effect.blip = {
  name: "character.box.effect.blip",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/blip",
};

/* Source File: flashDelta.mat */
Asset.prototype.material.character.box.effect.flashDelta = {
  name: "character.box.effect.flashDelta",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/flash_delta",
};

/* Source File: initialDelta.mat */
Asset.prototype.material.character.box.effect.initialDelta = {
  name: "character.box.effect.initialDelta",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/blip_init_delta",
};

/* Source File: spark.mat */
Asset.prototype.material.character.box.effect.spark = {
  name: "character.box.effect.spark",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/spark",
};

/* Source File: speedlineRB.mat */
Asset.prototype.material.character.box.effect.speedlineRB = {
  name: "character.box.effect.speedlineRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/speedline",
  texture1: "multi/red_low",
  texture2: "multi/white",
};

/* Source File: initialRB.mat */
Asset.prototype.material.character.box.effect.initialRB = {
  name: "character.box.effect.initialRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/blip_init",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: flash.mat */
Asset.prototype.material.character.box.effect.flash = {
  name: "character.box.effect.flash",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/box/effect/flash",
};

/* Source File: rewindpoint.mat */
Asset.prototype.material.character.xob.decal.rewindpoint = {
  name: "character.xob.decal.rewindpoint",
  shader: "decal_glow_noneg",
  shadow: "false",
  bloom: "false",
  texture0: "character/xob/decal/rewindpoint",
};

/* Source File: xob.mat */
Asset.prototype.material.character.xob.xob = {
  name: "character.xob.xob",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/xob/xob",
  texture1: "character/xob/xob_normal",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.xob.ui.iconsmall = {
  name: "character.xob.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/xob/ui/icon_sm",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.xob.ui.iconlarge = {
  name: "character.xob.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/xob/ui/icon_lg",
};

/* Source File: crate.mat */
Asset.prototype.material.character.crate.crate = {
  name: "character.crate.crate",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/crate/crate",
  texture1: "character/crate/crate_normal",
};

/* Source File: gold.mat */
Asset.prototype.material.character.crate.gold = {
  name: "character.crate.gold",
  shader: "playershiny",
  shadow: "true",
  bloom: "false",
  texture0: "character/crate/crate",
  texture1: "character/crate/crate_normal",
  texture2: "character/crate/gold",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: delta.mat */
Asset.prototype.material.character.crate.delta = {
  name: "character.crate.delta",
  shader: "playerdelta",
  shadow: "true",
  bloom: "false",
  texture0: "character/crate/crate",
  texture1: "character/crate/crate_normal",
  cube: ["multi/reflect/space0","multi/reflect/space1","multi/reflect/space2","multi/reflect/space3","multi/reflect/space4","multi/reflect/space5",],};

/* Source File: reverse.mat */
Asset.prototype.material.character.crate.reverse = {
  name: "character.crate.reverse",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/crate/reverse",
  texture1: "character/crate/crate_normal",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.crate.ui.iconsmall = {
  name: "character.crate.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/crate/ui/icon_sm",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.crate.ui.iconlarge = {
  name: "character.crate.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/crate/ui/icon_lg",
};

/* Source File: shockwaveRB.mat */
Asset.prototype.material.character.crate.effect.shockwaveRB = {
  name: "character.crate.effect.shockwaveRB",
  shader: "effectRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/crate/effect/shockwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: flashRB.mat */
Asset.prototype.material.character.crate.effect.flashRB = {
  name: "character.crate.effect.flashRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/crate/effect/flash",
  texture1: "multi/red_low",
  texture2: "multi/red_high",
};

/* Source File: blastRB.mat */
Asset.prototype.material.character.crate.effect.blastRB = {
  name: "character.crate.effect.blastRB",
  shader: "particleRB",
  shadow: "false",
  bloom: "false",
  texture0: "character/crate/effect/shockwave",
  texture1: "multi/rainbow_low",
  texture2: "multi/rainbow_high",
};

/* Source File: shockwave.mat */
Asset.prototype.material.character.crate.effect.shockwave = {
  name: "character.crate.effect.shockwave",
  shader: "effect2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/crate/effect/shockwave",
};

/* Source File: blast.mat */
Asset.prototype.material.character.crate.effect.blast = {
  name: "character.crate.effect.blast",
  shader: "particle2tone",
  shadow: "false",
  bloom: "false",
  texture0: "character/crate/effect/shockwave",
};

/* Source File: flash.mat */
Asset.prototype.material.character.crate.effect.flash = {
  name: "character.crate.effect.flash",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "character/crate/effect/flash",
};

/* Source File: inferno.mat */
Asset.prototype.material.character.inferno.inferno = {
  name: "character.inferno.inferno",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/inferno/inferno",
  texture1: "character/inferno/inferno_normal",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.inferno.ui.iconsmall = {
  name: "character.inferno.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/inferno/ui/icon_sm",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.inferno.ui.iconlarge = {
  name: "character.inferno.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/inferno/ui/icon_lg",
};

/* Source File: bloodsplatsmall.mat */
Asset.prototype.material.character.generic.decal.bloodsplatsmall = {
  name: "character.generic.decal.bloodsplatsmall",
  shader: "decal",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/decal/bloodsplatsmall",
  texture1: "character/generic/decal/bloodsplatsmallnormal",
};

/* Source File: targetcircle.mat */
Asset.prototype.material.character.generic.decal.targetcircle = {
  name: "character.generic.decal.targetcircle",
  shader: "decal_glow_noneg",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/decal/targetdecal",
};

/* Source File: bloodsplat.mat */
Asset.prototype.material.character.generic.decal.bloodsplat = {
  name: "character.generic.decal.bloodsplat",
  shader: "decal",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/decal/bloodsplat",
  texture1: "character/generic/decal/bloodsplatnormal",
};

/* Source File: altflame.mat */
Asset.prototype.material.character.generic.ui.altflame = {
  name: "character.generic.ui.altflame",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_flame",
};

/* Source File: altdelta.mat */
Asset.prototype.material.character.generic.ui.altdelta = {
  name: "character.generic.ui.altdelta",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_delta",
};

/* Source File: iconsmall.mat */
Asset.prototype.material.character.generic.ui.iconsmall = {
  name: "character.generic.ui.iconsmall",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/icon_lg",
};

/* Source File: althit.mat */
Asset.prototype.material.character.generic.ui.althit = {
  name: "character.generic.ui.althit",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_hit",
};

/* Source File: altgold.mat */
Asset.prototype.material.character.generic.ui.altgold = {
  name: "character.generic.ui.altgold",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_gold",
};

/* Source File: althat.mat */
Asset.prototype.material.character.generic.ui.althat = {
  name: "character.generic.ui.althat",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_hat",
};

/* Source File: metera.mat */
Asset.prototype.material.character.generic.ui.metera = {
  name: "character.generic.ui.metera",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/meter_a",
};

/* Source File: meterb.mat */
Asset.prototype.material.character.generic.ui.meterb = {
  name: "character.generic.ui.meterb",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/meter_b",
};

/* Source File: meterstub.mat */
Asset.prototype.material.character.generic.ui.meterstub = {
  name: "character.generic.ui.meterstub",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/meterstub",
};

/* Source File: altcolor.mat */
Asset.prototype.material.character.generic.ui.altcolor = {
  name: "character.generic.ui.altcolor",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_color",
};

/* Source File: altdark.mat */
Asset.prototype.material.character.generic.ui.altdark = {
  name: "character.generic.ui.altdark",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_dark",
};

/* Source File: altround.mat */
Asset.prototype.material.character.generic.ui.altround = {
  name: "character.generic.ui.altround",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_round",
};

/* Source File: altretro.mat */
Asset.prototype.material.character.generic.ui.altretro = {
  name: "character.generic.ui.altretro",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_retro",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.generic.ui.iconlarge = {
  name: "character.generic.ui.iconlarge",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/icon_lg",
};

/* Source File: altrainbow.mat */
Asset.prototype.material.character.generic.ui.altrainbow = {
  name: "character.generic.ui.altrainbow",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_rainbow",
};

/* Source File: altvoice.mat */
Asset.prototype.material.character.generic.ui.altvoice = {
  name: "character.generic.ui.altvoice",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/ui/alt_voice",
};

/* Source File: grey.mat */
Asset.prototype.material.character.generic.grey = {
  name: "character.generic.grey",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/generic/grey",
  texture1: "character/generic/normal",
};

/* Source File: white.mat */
Asset.prototype.material.character.generic.white = {
  name: "character.generic.white",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "character/generic/white",
  texture1: "character/generic/normal",
};

/* Source File: star.mat */
Asset.prototype.material.character.generic.effect.star = {
  name: "character.generic.effect.star",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/effect/star",
};

/* Source File: airjump.mat */
Asset.prototype.material.character.generic.effect.airjump = {
  name: "character.generic.effect.airjump",
  shader: "effect",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/effect/airjump",
};

/* Source File: blooddrop.mat */
Asset.prototype.material.character.generic.effect.blooddrop = {
  name: "character.generic.effect.blooddrop",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/effect/blooddrop",
};

/* Source File: bloodsplash.mat */
Asset.prototype.material.character.generic.effect.bloodsplash = {
  name: "character.generic.effect.bloodsplash",
  shader: "particle",
  shadow: "false",
  bloom: "false",
  texture0: "character/generic/effect/bloodsplash",
};

/* Source File: comet.mat */
Asset.prototype.material.sky.vapor.comet = {
  name: "sky.vapor.comet",
  shader: "finalcomet",
  shadow: "false",
  bloom: "false",
  texture0: "sky/final/comet",
  texture1: "sky/vapor/grad",
};

/* Source File: grid.mat */
Asset.prototype.material.sky.vapor.grid = {
  name: "sky.vapor.grid",
  shader: "skyvaporgrid",
  shadow: "false",
  bloom: "false",
  texture0: "sky/vapor/grid",
  texture1: "sky/final/mask",
};

/* Source File: sky.mat */
Asset.prototype.material.sky.gold.sky = {
  name: "sky.gold.sky",
  shader: "skygoldsky",
  shadow: "false",
  bloom: "false",
  texture0: "sky/gold/sky",
};

/* Source File: cloud.mat */
Asset.prototype.material.sky.gold.cloud = {
  name: "sky.gold.cloud",
  shader: "skygoldcloud",
  shadow: "false",
  bloom: "false",
  texture0: "sky/gold/cloud",
};

/* Source File: void.mat */
Asset.prototype.material.sky.gold.void = {
  name: "sky.gold.void",
  shader: "skygoldsky",
  shadow: "false",
  bloom: "false",
  texture0: "sky/gold/void",
};

/* Source File: outer.mat */
Asset.prototype.material.sky.final.outer = {
  name: "sky.final.outer",
  shader: "finalout",
  shadow: "false",
  bloom: "false",
  texture0: "sky/final/mask",
  texture1: "sky/final/star_multi",
};

/* Source File: comet.mat */
Asset.prototype.material.sky.final.comet = {
  name: "sky.final.comet",
  shader: "finalcomet",
  shadow: "false",
  bloom: "false",
  texture0: "sky/final/comet",
  texture1: "sky/final/rainbow",
};

/* Source File: space.mat */
Asset.prototype.material.sky.final.space = {
  name: "sky.final.space",
  shader: "finalspace",
  shadow: "false",
  bloom: "false",
  texture0: "sky/final/space",
  texture1: "sky/final/mask",
  texture2: "sky/final/star_multi",
};

/* Source File: inner.mat */
Asset.prototype.material.sky.final.inner = {
  name: "sky.final.inner",
  shader: "finalin",
  shadow: "false",
  bloom: "false",
  texture0: "sky/final/nebula_multi",
  texture1: "sky/final/nebula_color",
  texture2: "sky/final/mask",
};

/* Source File: thumbin.mat */
Asset.prototype.material.ui.thumbin = {
  name: "ui.thumbin",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/thumbin",
};

/* Source File: calibri.mat */
Asset.prototype.material.ui.calibri = {
  name: "ui.calibri",
  shader: "font",
  shadow: "false",
  bloom: "false",
  texture0: "ui/calibri",
};

/* Source File: tutorial0.mat */
Asset.prototype.material.ui.tutorial.tutorial0 = {
  name: "ui.tutorial.tutorial0",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/tutorial/tutorial0",
};

/* Source File: tutorial1.mat */
Asset.prototype.material.ui.tutorial.tutorial1 = {
  name: "ui.tutorial.tutorial1",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/tutorial/tutorial1",
};

/* Source File: tutorial2.mat */
Asset.prototype.material.ui.tutorial.tutorial2 = {
  name: "ui.tutorial.tutorial2",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/tutorial/tutorial2",
};

/* Source File: zone.mat */
Asset.prototype.material.ui.zone = {
  name: "ui.zone",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/zone",
};

/* Source File: credit.mat */
Asset.prototype.material.ui.credit = {
  name: "ui.credit",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/credit",
};

/* Source File: ultimate.mat */
Asset.prototype.material.ui.ultimate = {
  name: "ui.ultimate",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/ultimate",
};

/* Source File: color.mat */
Asset.prototype.material.ui.color = {
  name: "ui.color",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/white",
};

/* Source File: flag.mat */
Asset.prototype.material.ui.flag = {
  name: "ui.flag",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/flag",
};

/* Source File: king.mat */
Asset.prototype.material.ui.king = {
  name: "ui.king",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/king",
};

/* Source File: thumbout.mat */
Asset.prototype.material.ui.thumbout = {
  name: "ui.thumbout",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/thumbout",
};

/* Source File: bomb.mat */
Asset.prototype.material.ui.bomb = {
  name: "ui.bomb",
  shader: "simpletrans",
  shadow: "false",
  bloom: "false",
  texture0: "ui/bomb",
};

/* Source File: metal_dark.mat */
Asset.prototype.material.map.copper.metal_dark = {
  name: "map.copper.metal_dark",
  shader: "tin",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/copper/metal_dark",
  texture1: "map/copper/flat_normal",
  texture2: "map/copper/edge_color",
  texture3: "multi/multi_dif",
};

/* Source File: metal_light.mat */
Asset.prototype.material.map.copper.metal_light = {
  name: "map.copper.metal_light",
  shader: "tin",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/copper/metal",
  texture1: "map/copper/flat_normal",
  texture2: "map/copper/edge_color",
  texture3: "multi/multi_dif",
};

/* Source File: box.mat */
Asset.prototype.material.map.copper.box = {
  name: "map.copper.box",
  shader: "cube",
  shadow: "false",
  bloom: "cube",
  texture0: "map/copper/cube",
  texture1: "multi/multi_dif",
};

/* Source File: metal_rough.mat */
Asset.prototype.material.map.copper.metal_rough = {
  name: "map.copper.metal_rough",
  shader: "copper_wall",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/copper/metal_rough",
  texture1: "map/copper/cross_normal",
  texture2: "map/copper/edge_color",
  texture3: "multi/multi_dif",
};

/* Source File: light.mat */
Asset.prototype.material.map.copper.light = {
  name: "map.copper.light",
  shader: "glow",
  shadow: "true",
  bloom: "glow",
  texture0: "map/copper/light",
};

/* Source File: field.mat */
Asset.prototype.material.map.copper.field = {
  name: "map.copper.field",
  shader: "glow",
  shadow: "false",
  bloom: "false",
  texture0: "map/copper/light",
};

/* Source File: lily.mat */
Asset.prototype.material.map.gold.lily = {
  name: "map.gold.lily",
  shader: "goldmask",
  shadow: "mask",
  bloom: "false",
  texture0: "map/gold/lily",
};

/* Source File: dandelion.mat */
Asset.prototype.material.map.gold.dandelion = {
  name: "map.gold.dandelion",
  shader: "goldmask",
  shadow: "mask",
  bloom: "false",
  texture0: "map/gold/flower_dandelion",
};

/* Source File: lamp.mat */
Asset.prototype.material.map.gold.lamp = {
  name: "map.gold.lamp",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/redstone_lamp_on",
};

/* Source File: sand.mat */
Asset.prototype.material.map.gold.sand = {
  name: "map.gold.sand",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/sand",
};

/* Source File: coal.mat */
Asset.prototype.material.map.gold.coal = {
  name: "map.gold.coal",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/coal_ore",
};

/* Source File: water.mat */
Asset.prototype.material.map.gold.water = {
  name: "map.gold.water",
  shader: "goldwater",
  shadow: "false",
  bloom: "false",
  texture0: "map/gold/water",
};

/* Source File: wood.mat */
Asset.prototype.material.map.gold.wood = {
  name: "map.gold.wood",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/planks_oak",
};

/* Source File: gold.mat */
Asset.prototype.material.map.gold.gold = {
  name: "map.gold.gold",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/gold_ore",
};

/* Source File: rose.mat */
Asset.prototype.material.map.gold.rose = {
  name: "map.gold.rose",
  shader: "goldmask",
  shadow: "mask",
  bloom: "false",
  texture0: "map/gold/flower_rose",
};

/* Source File: path.mat */
Asset.prototype.material.map.gold.path = {
  name: "map.gold.path",
  shader: "gold2x",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/path",
};

/* Source File: reed.mat */
Asset.prototype.material.map.gold.reed = {
  name: "map.gold.reed",
  shader: "goldmask",
  shadow: "mask",
  bloom: "false",
  texture0: "map/gold/reeds",
};

/* Source File: dirt.mat */
Asset.prototype.material.map.gold.dirt = {
  name: "map.gold.dirt",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/dirt",
};

/* Source File: tallGrass.mat */
Asset.prototype.material.map.gold.tallGrass = {
  name: "map.gold.tallGrass",
  shader: "goldmask",
  shadow: "mask",
  bloom: "false",
  texture0: "map/gold/tallgrass",
};

/* Source File: book.mat */
Asset.prototype.material.map.gold.book = {
  name: "map.gold.book",
  shader: "gold2x",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/book",
};

/* Source File: cobble.mat */
Asset.prototype.material.map.gold.cobble = {
  name: "map.gold.cobble",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/cobblestone",
};

/* Source File: slab.mat */
Asset.prototype.material.map.gold.slab = {
  name: "map.gold.slab",
  shader: "gold2x",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/slab",
};

/* Source File: bedrock.mat */
Asset.prototype.material.map.gold.bedrock = {
  name: "map.gold.bedrock",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/bedrock",
};

/* Source File: fern.mat */
Asset.prototype.material.map.gold.fern = {
  name: "map.gold.fern",
  shader: "goldmask",
  shadow: "false",
  bloom: "false",
  texture0: "map/gold/fern",
};

/* Source File: lava.mat */
Asset.prototype.material.map.gold.lava = {
  name: "map.gold.lava",
  shader: "goldlava",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/lava",
};

/* Source File: gravel.mat */
Asset.prototype.material.map.gold.gravel = {
  name: "map.gold.gravel",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/gravel",
};

/* Source File: iron.mat */
Asset.prototype.material.map.gold.iron = {
  name: "map.gold.iron",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/iron_ore",
};

/* Source File: farm.mat */
Asset.prototype.material.map.gold.farm = {
  name: "map.gold.farm",
  shader: "gold2x",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/farm",
};

/* Source File: grass.mat */
Asset.prototype.material.map.gold.grass = {
  name: "map.gold.grass",
  shader: "gold2x",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/grass",
};

/* Source File: wheat.mat */
Asset.prototype.material.map.gold.wheat = {
  name: "map.gold.wheat",
  shader: "goldmask",
  shadow: "mask",
  bloom: "false",
  texture0: "map/gold/wheat_stage_7",
};

/* Source File: sapling.mat */
Asset.prototype.material.map.gold.sapling = {
  name: "map.gold.sapling",
  shader: "goldmask",
  shadow: "mask",
  bloom: "false",
  texture0: "map/gold/sapling_oak",
};

/* Source File: pimp.mat */
Asset.prototype.material.map.gold.pimp = {
  name: "map.gold.pimp",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/gold_block",
};

/* Source File: stone.mat */
Asset.prototype.material.map.gold.stone = {
  name: "map.gold.stone",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/stone",
};

/* Source File: leaves.mat */
Asset.prototype.material.map.gold.leaves = {
  name: "map.gold.leaves",
  shader: "goldmask",
  shadow: "mask",
  bloom: "false",
  texture0: "map/gold/leaves",
};

/* Source File: log.mat */
Asset.prototype.material.map.gold.log = {
  name: "map.gold.log",
  shader: "gold2x",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/log",
};

/* Source File: brick.mat */
Asset.prototype.material.map.gold.brick = {
  name: "map.gold.brick",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/stonebrick",
};

/* Source File: carved.mat */
Asset.prototype.material.map.gold.carved = {
  name: "map.gold.carved",
  shader: "gold",
  shadow: "true",
  bloom: "false",
  texture0: "map/gold/stonebrick_carved",
};

/* Source File: metal_dark.mat */
Asset.prototype.material.map.iron.metal_dark = {
  name: "map.iron.metal_dark",
  shader: "tin",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/iron/metal_dark",
  texture1: "map/iron/flat_normal",
  texture2: "map/iron/edge_color",
  texture3: "multi/multi_dif",
};

/* Source File: metal_light.mat */
Asset.prototype.material.map.iron.metal_light = {
  name: "map.iron.metal_light",
  shader: "tin",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/iron/metal",
  texture1: "map/iron/flat_normal",
  texture2: "map/iron/edge_color",
  texture3: "multi/multi_dif",
};

/* Source File: orb.mat */
Asset.prototype.material.map.iron.orb = {
  name: "map.iron.orb",
  shader: "orb",
  shadow: "false",
  bloom: "orb",
  texture0: "multi/multi_dif",
};

/* Source File: plasma.mat */
Asset.prototype.material.map.iron.plasma = {
  name: "map.iron.plasma",
  shader: "ironplasma",
  shadow: "false",
  bloom: "false",
  texture0: "map/iron/edge_color",
  texture1: "multi/multi_dif",
  texture2: "map/iron/plasma_mask",
};

/* Source File: metal_rough.mat */
Asset.prototype.material.map.iron.metal_rough = {
  name: "map.iron.metal_rough",
  shader: "tin",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/iron/metal_rough",
  texture1: "map/iron/metal_rough_normal",
  texture2: "map/iron/edge_color",
  texture3: "multi/multi_dif",
};

/* Source File: grid.mat */
Asset.prototype.material.map.iron.grid = {
  name: "map.iron.grid",
  shader: "tin_grid",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/iron/grid",
  texture1: "map/iron/flat_normal",
  texture2: "map/iron/edge_color",
  texture3: "multi/multi_dif",
  texture4: "map/iron/grid_multi",
};

/* Source File: light.mat */
Asset.prototype.material.map.iron.light = {
  name: "map.iron.light",
  shader: "glow",
  shadow: "true",
  bloom: "glow",
  texture0: "map/iron/light",
};

/* Source File: metal_dark.mat */
Asset.prototype.material.map.tin.metal_dark = {
  name: "map.tin.metal_dark",
  shader: "tin",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/tin/metal_dark",
  texture1: "map/tin/flat_normal",
  texture2: "map/tin/edge_color",
  texture3: "multi/multi_dif",
};

/* Source File: metal_light.mat */
Asset.prototype.material.map.tin.metal_light = {
  name: "map.tin.metal_light",
  shader: "tin",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/tin/metal",
  texture1: "map/tin/flat_normal",
  texture2: "map/tin/edge_color",
  texture3: "multi/multi_dif",
};

/* Source File: orb.mat */
Asset.prototype.material.map.tin.orb = {
  name: "map.tin.orb",
  shader: "orb",
  shadow: "false",
  bloom: "orb",
  texture0: "multi/multi_dif",
};

/* Source File: metal_rough.mat */
Asset.prototype.material.map.tin.metal_rough = {
  name: "map.tin.metal_rough",
  shader: "tin",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/tin/metal_rough",
  texture1: "map/tin/metal_rough_normal",
  texture2: "map/tin/edge_color",
  texture3: "multi/multi_dif",
};

/* Source File: grid.mat */
Asset.prototype.material.map.tin.grid = {
  name: "map.tin.grid",
  shader: "tin_grid",
  shadow: "true",
  bloom: "mapbloom_negx",
  texture0: "map/tin/grid",
  texture1: "map/tin/flat_normal",
  texture2: "map/tin/edge_color",
  texture3: "multi/multi_dif",
  texture4: "map/tin/grid_multi",
};

/* Source File: light.mat */
Asset.prototype.material.map.tin.light = {
  name: "map.tin.light",
  shader: "glow",
  shadow: "true",
  bloom: "glow",
  texture0: "map/tin/light",
};

/* Source File: bomb.mat */
Asset.prototype.material.object.bomb.bomb = {
  name: "object.bomb.bomb",
  shader: "default",
  shadow: "true",
  bloom: "false",
  texture0: "object/bomb/bomb",
  texture1: "multi/normal",
};

/* Source File: zone.mat */
Asset.prototype.material.object.zone.zone = {
  name: "object.zone.zone",
  shader: "zone",
  shadow: "false",
  bloom: "false",
  texture0: "multi/default",
  texture1: "object/zone/gradient",
};

/* Source File: flag.mat */
Asset.prototype.material.object.flag.flag = {
  name: "object.flag.flag",
  shader: "player",
  shadow: "true",
  bloom: "false",
  texture0: "multi/default",
  texture1: "multi/normal",
};

/* Source File: hill.mat */
Asset.prototype.material.object.hill.hill = {
  name: "object.hill.hill",
  shader: "zone",
  shadow: "false",
  bloom: "false",
  texture0: "multi/default",
  texture1: "object/hill/gradient",
};

/* Source File: targetcircle.mat */
Asset.prototype.material.object.generic.decal.targetcircle = {
  name: "object.generic.decal.targetcircle",
  shader: "decal_glow_noneg",
  shadow: "false",
  bloom: "false",
  texture0: "object/generic/decal/targetcircle",
};

/* Source File: targetcirclesm.mat */
Asset.prototype.material.object.generic.decal.targetcirclesm = {
  name: "object.generic.decal.targetcirclesm",
  shader: "decal_glow_noneg",
  shadow: "false",
  bloom: "false",
  texture0: "object/generic/decal/targetcircle-sm",
};

