"use strict";
/* global Asset */

/* This JS file was generated by NoxioAssetConverter */
Asset.prototype.material = {};
Asset.prototype.material.ui = {};
Asset.prototype.material.multi = {};
Asset.prototype.material.test = {};
Asset.prototype.material.effect = {};
Asset.prototype.material.prank = {};

/* Source File: grey.mat */
Asset.prototype.material.ui.grey = {
  name: "material.ui.grey",
  shader: "simpletrans",
  shadow: false,
  texture0: "ui/grey",
};

/* Source File: white.mat */
Asset.prototype.material.ui.white = {
  name: "material.ui.white",
  shader: "simpletrans",
  shadow: false,
  texture0: "ui/white",
};

/* Source File: white_solid.mat */
Asset.prototype.material.ui.white_solid = {
  name: "material.ui.white_solid",
  shader: "simpletrans",
  shadow: false,
  texture0: "ui/white_solid",
};

/* Source File: post_msaa.mat */
Asset.prototype.material.multi.post_msaa = {
  name: "material.multi.post_msaa",
  shader: "post_msaa",
  shadow: false,
};

/* Source File: gulm.mat */
Asset.prototype.material.multi.gulm = {
  name: "material.multi.gulm",
  shader: "font",
  shadow: false,
  texture0: "multi/gulm_sdf",
};

/* Source File: default.mat */
Asset.prototype.material.multi.default = {
  name: "material.multi.default",
  shader: "default",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: post.mat */
Asset.prototype.material.multi.post = {
  name: "material.multi.post",
  shader: "post",
  shadow: false,
};

/* Source File: shadow.mat */
Asset.prototype.material.multi.shadow = {
  name: "material.multi.shadow",
  shader: "shadow",
  shadow: true,
};

/* Source File: post_fxaa.mat */
Asset.prototype.material.multi.post_fxaa = {
  name: "material.multi.post_fxaa",
  shader: "post_fxaa",
  shadow: false,
};

/* Source File: test3.mat */
Asset.prototype.material.test.test3 = {
  name: "material.test.test3",
  shader: "test",
  shadow: true,
  texture0: "test/banned",
};

/* Source File: test1.mat */
Asset.prototype.material.test.test1 = {
  name: "material.test.test1",
  shader: "test",
  shadow: true,
  texture0: "test/pointdown",
};

/* Source File: test2.mat */
Asset.prototype.material.test.test2 = {
  name: "material.test.test2",
  shader: "test",
  shadow: true,
  texture0: "test/fat",
};

/* Source File: shockwave.mat */
Asset.prototype.material.effect.shockwave = {
  name: "material.effect.shockwave",
  shader: "particle",
  shadow: false,
  texture0: "effect/shockwave",
};

/* Source File: star.mat */
Asset.prototype.material.effect.star = {
  name: "material.effect.star",
  shader: "particle",
  shadow: false,
  texture0: "effect/star",
};

/* Source File: speedline.mat */
Asset.prototype.material.effect.speedline = {
  name: "material.effect.speedline",
  shader: "particle",
  shadow: false,
  texture0: "effect/speedline",
};

/* Source File: spark.mat */
Asset.prototype.material.effect.spark = {
  name: "material.effect.spark",
  shader: "particle",
  shadow: false,
  texture0: "effect/spark",
};

/* Source File: blipBright.mat */
Asset.prototype.material.prank.blipBright = {
  name: "material.prank.blipBright",
  shader: "particle",
  shadow: false,
  texture0: "prank/blip_bright",
};

/* Source File: blipIcon.mat */
Asset.prototype.material.prank.blipIcon = {
  name: "material.prank.blipIcon",
  shader: "simpletrans",
  shadow: false,
  texture0: "prank/blip_icon",
};

/* Source File: blip.mat */
Asset.prototype.material.prank.blip = {
  name: "material.prank.blip",
  shader: "particle",
  shadow: false,
  texture0: "prank/blip",
};

/* Source File: dashIcon.mat */
Asset.prototype.material.prank.dashIcon = {
  name: "material.prank.dashIcon",
  shader: "simpletrans",
  shadow: false,
  texture0: "prank/dash_icon",
};

