"use strict";
/* global Asset */

/* This JS file was generated by NoxioAssetConverter */
Asset.prototype.material = {};
Asset.prototype.material.ui = {};
Asset.prototype.material.multi = {};
Asset.prototype.material.character = {};
Asset.prototype.material.character.player = {};
Asset.prototype.material.character.player.decal = {};
Asset.prototype.material.character.player.effect = {};
Asset.prototype.material.character.fox = {};
Asset.prototype.material.character.fox.ui = {};
Asset.prototype.material.character.fox.decal = {};
Asset.prototype.material.character.fox.effect = {};
Asset.prototype.material.sky = {};
Asset.prototype.material.sky.final = {};
Asset.prototype.material.map = {};
Asset.prototype.material.map.final = {};

/* Source File: gulm.mat */
Asset.prototype.material.ui.gulm = {
  name: "ui.gulm",
  shader: "font",
  shadow: false,
  texture0: "ui/gulm_sdf",
};

/* Source File: flagIcon.mat */
Asset.prototype.material.ui.flagIcon = {
  name: "ui.flagIcon",
  shader: "simpletrans",
  shadow: false,
  texture0: "ui/flag",
};

/* Source File: grey.mat */
Asset.prototype.material.ui.grey = {
  name: "ui.grey",
  shader: "simpletrans",
  shadow: false,
  texture0: "ui/grey",
};

/* Source File: white.mat */
Asset.prototype.material.ui.white = {
  name: "ui.white",
  shader: "simpletrans",
  shadow: false,
  texture0: "ui/white",
};

/* Source File: white_solid.mat */
Asset.prototype.material.ui.white_solid = {
  name: "ui.white_solid",
  shader: "simpletrans",
  shadow: false,
  texture0: "ui/white_solid",
};

/* Source File: post_msaa.mat */
Asset.prototype.material.multi.post_msaa = {
  name: "multi.post_msaa",
  shader: "post_msaa",
  shadow: false,
};

/* Source File: default.mat */
Asset.prototype.material.multi.default = {
  name: "multi.default",
  shader: "default",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: post.mat */
Asset.prototype.material.multi.post = {
  name: "multi.post",
  shader: "post",
  shadow: false,
};

/* Source File: shadow.mat */
Asset.prototype.material.multi.shadow = {
  name: "multi.shadow",
  shader: "shadow",
  shadow: true,
};

/* Source File: post_fxaa.mat */
Asset.prototype.material.multi.post_fxaa = {
  name: "multi.post_fxaa",
  shader: "post_fxaa",
  shadow: false,
};

/* Source File: targetcircle.mat */
Asset.prototype.material.character.player.decal.targetcircle = {
  name: "character.player.decal.targetcircle",
  shader: "decal_glow",
  shadow: false,
  texture0: "character/player/decal/targetcircle",
};

/* Source File: bloodsplat.mat */
Asset.prototype.material.character.player.decal.bloodsplat = {
  name: "character.player.decal.bloodsplat",
  shader: "decal",
  shadow: false,
  texture0: "character/player/decal/bloodsplat",
};

/* Source File: bloodsplatsmall.mat */
Asset.prototype.material.character.player.decal.bloodsplatsmall = {
  name: "character.player.decal.bloodsplatsmall",
  shader: "decal",
  shadow: false,
  texture0: "character/player/decal/bloodsplatsmall",
};

/* Source File: star.mat */
Asset.prototype.material.character.player.effect.star = {
  name: "character.player.effect.star",
  shader: "particle",
  shadow: false,
  texture0: "character/player/effect/star",
};

/* Source File: bloodsplash.mat */
Asset.prototype.material.character.player.effect.bloodsplash = {
  name: "character.player.effect.bloodsplash",
  shader: "particle",
  shadow: false,
  texture0: "character/player/effect/bloodsplash",
};

/* Source File: blooddrop.mat */
Asset.prototype.material.character.player.effect.blooddrop = {
  name: "character.player.effect.blooddrop",
  shader: "particle",
  shadow: false,
  texture0: "character/player/effect/blooddrop",
};

/* Source File: blipIcon.mat */
Asset.prototype.material.character.fox.ui.blipIcon = {
  name: "character.fox.ui.blipIcon",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/fox/ui/blip_icon",
};

/* Source File: dashIcon.mat */
Asset.prototype.material.character.fox.ui.dashIcon = {
  name: "character.fox.ui.dashIcon",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/fox/ui/dash_icon",
};

/* Source File: shockwave.mat */
Asset.prototype.material.character.fox.effect.shockwave = {
  name: "character.fox.effect.shockwave",
  shader: "particle",
  shadow: false,
  texture0: "character/fox/effect/shockwave",
};

/* Source File: speedline.mat */
Asset.prototype.material.character.fox.effect.speedline = {
  name: "character.fox.effect.speedline",
  shader: "particle",
  shadow: false,
  texture0: "character/fox/effect/speedline",
};

/* Source File: blipBright.mat */
Asset.prototype.material.character.fox.effect.blipBright = {
  name: "character.fox.effect.blipBright",
  shader: "particle",
  shadow: false,
  texture0: "character/fox/effect/blip_bright",
};

/* Source File: spark.mat */
Asset.prototype.material.character.fox.effect.spark = {
  name: "character.fox.effect.spark",
  shader: "particle",
  shadow: false,
  texture0: "character/fox/effect/spark",
};

/* Source File: blip.mat */
Asset.prototype.material.character.fox.effect.blip = {
  name: "character.fox.effect.blip",
  shader: "particle",
  shadow: false,
  texture0: "character/fox/effect/blip",
};

/* Source File: sky.mat */
Asset.prototype.material.sky.final.sky = {
  name: "sky.final.sky",
  shader: "final_space",
  shadow: false,
  texture0: "sky/final/space_color",
  texture1: "sky/final/lines",
  texture2: "sky/final/multi_space",
  texture3: "sky/final/twink",
  texture4: "sky/final/multi_difference",
};

/* Source File: grid.mat */
Asset.prototype.material.map.final.grid = {
  name: "map.final.grid",
  shader: "final_grid",
  shadow: false,
  texture0: "map/final/grid",
};

/* Source File: ceiling.mat */
Asset.prototype.material.map.final.ceiling = {
  name: "map.final.ceiling",
  shader: "final",
  shadow: true,
  texture0: "map/final/stage_dark",
  texture1: "map/final/edge_color",
};

/* Source File: floor.mat */
Asset.prototype.material.map.final.floor = {
  name: "map.final.floor",
  shader: "final",
  shadow: true,
  texture0: "map/final/stage",
  texture1: "map/final/edge_color",
};

/* Source File: wall.mat */
Asset.prototype.material.map.final.wall = {
  name: "map.final.wall",
  shader: "final",
  shadow: true,
  texture0: "map/final/stage",
  texture1: "map/final/edge_color",
};

