"use strict";
/* global Asset */

/* This JS file was generated by NoxioAssetConverter */
Asset.prototype.material = {};
Asset.prototype.material.object = {};
Asset.prototype.material.object.flag = {};
Asset.prototype.material.object.bomb = {};
Asset.prototype.material.ui = {};
Asset.prototype.material.multi = {};
Asset.prototype.material.multi.hitbox = {};
Asset.prototype.material.character = {};
Asset.prototype.material.character.puff = {};
Asset.prototype.material.character.puff.ui = {};
Asset.prototype.material.character.falco = {};
Asset.prototype.material.character.falco.ui = {};
Asset.prototype.material.character.falco.effect = {};
Asset.prototype.material.character.player = {};
Asset.prototype.material.character.player.ui = {};
Asset.prototype.material.character.player.decal = {};
Asset.prototype.material.character.player.effect = {};
Asset.prototype.material.character.marth = {};
Asset.prototype.material.character.marth.ui = {};
Asset.prototype.material.character.marth.effect = {};
Asset.prototype.material.character.captain = {};
Asset.prototype.material.character.captain.ui = {};
Asset.prototype.material.character.shiek = {};
Asset.prototype.material.character.shiek.ui = {};
Asset.prototype.material.character.shiek.effect = {};
Asset.prototype.material.character.inferno = {};
Asset.prototype.material.character.inferno.ui = {};
Asset.prototype.material.character.fox = {};
Asset.prototype.material.character.fox.ui = {};
Asset.prototype.material.character.fox.decal = {};
Asset.prototype.material.character.fox.effect = {};
Asset.prototype.material.sky = {};
Asset.prototype.material.sky.final = {};
Asset.prototype.material.map = {};
Asset.prototype.material.map.final = {};

/* Source File: flag.mat */
Asset.prototype.material.object.flag.flag = {
  name: "object.flag.flag",
  shader: "player",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: bomb.mat */
Asset.prototype.material.object.bomb.bomb = {
  name: "object.bomb.bomb",
  shader: "player",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: flag.mat */
Asset.prototype.material.ui.flag = {
  name: "ui.flag",
  shader: "simpletrans",
  shadow: false,
  texture0: "ui/flag",
};

/* Source File: color.mat */
Asset.prototype.material.ui.color = {
  name: "ui.color",
  shader: "simpletrans",
  shadow: false,
  texture0: "ui/white",
};

/* Source File: calibri.mat */
Asset.prototype.material.ui.calibri = {
  name: "ui.calibri",
  shader: "font",
  shadow: false,
  texture0: "ui/calibri",
};

/* Source File: hitbox.mat */
Asset.prototype.material.multi.hitbox.hitbox = {
  name: "multi.hitbox.hitbox",
  shader: "effect",
  shadow: false,
  texture0: "multi/default",
};

/* Source File: post_msaa.mat */
Asset.prototype.material.multi.post_msaa = {
  name: "multi.post_msaa",
  shader: "post_msaa",
  shadow: false,
};

/* Source File: default.mat */
Asset.prototype.material.multi.default = {
  name: "multi.default",
  shader: "default",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: post.mat */
Asset.prototype.material.multi.post = {
  name: "multi.post",
  shader: "post",
  shadow: false,
};

/* Source File: shadow.mat */
Asset.prototype.material.multi.shadow = {
  name: "multi.shadow",
  shader: "shadow",
  shadow: true,
};

/* Source File: post_fxaa.mat */
Asset.prototype.material.multi.post_fxaa = {
  name: "multi.post_fxaa",
  shader: "post_fxaa",
  shadow: false,
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.puff.ui.iconlarge = {
  name: "character.puff.ui.iconlarge",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/puff/ui/icon_lg",
};

/* Source File: puff.mat */
Asset.prototype.material.character.puff.puff = {
  name: "character.puff.puff",
  shader: "player",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.falco.ui.iconlarge = {
  name: "character.falco.ui.iconlarge",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/falco/ui/icon_lg",
};

/* Source File: falco.mat */
Asset.prototype.material.character.falco.falco = {
  name: "character.falco.falco",
  shader: "player",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: charge.mat */
Asset.prototype.material.character.falco.effect.charge = {
  name: "character.falco.effect.charge",
  shader: "effect_fire_plane",
  shadow: false,
  texture0: "character/falco/effect/chargemask",
  texture1: "character/falco/effect/firecolor",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.player.ui.iconlarge = {
  name: "character.player.ui.iconlarge",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/player/ui/icon_lg",
};

/* Source File: targetcircle.mat */
Asset.prototype.material.character.player.decal.targetcircle = {
  name: "character.player.decal.targetcircle",
  shader: "decal_glow",
  shadow: false,
  texture0: "character/player/decal/targetcircle",
};

/* Source File: bloodsplat.mat */
Asset.prototype.material.character.player.decal.bloodsplat = {
  name: "character.player.decal.bloodsplat",
  shader: "decal",
  shadow: false,
  texture0: "character/player/decal/bloodsplat",
};

/* Source File: bloodsplatsmall.mat */
Asset.prototype.material.character.player.decal.bloodsplatsmall = {
  name: "character.player.decal.bloodsplatsmall",
  shader: "decal",
  shadow: false,
  texture0: "character/player/decal/bloodsplatsmall",
};

/* Source File: star.mat */
Asset.prototype.material.character.player.effect.star = {
  name: "character.player.effect.star",
  shader: "particle",
  shadow: false,
  texture0: "character/player/effect/star",
};

/* Source File: bloodsplash.mat */
Asset.prototype.material.character.player.effect.bloodsplash = {
  name: "character.player.effect.bloodsplash",
  shader: "particle",
  shadow: false,
  texture0: "character/player/effect/bloodsplash",
};

/* Source File: airjump.mat */
Asset.prototype.material.character.player.effect.airjump = {
  name: "character.player.effect.airjump",
  shader: "effect",
  shadow: false,
  texture0: "character/player/effect/airjump",
};

/* Source File: blooddrop.mat */
Asset.prototype.material.character.player.effect.blooddrop = {
  name: "character.player.effect.blooddrop",
  shader: "particle",
  shadow: false,
  texture0: "character/player/effect/blooddrop",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.marth.ui.iconlarge = {
  name: "character.marth.ui.iconlarge",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/marth/ui/icon_lg",
};

/* Source File: marth.mat */
Asset.prototype.material.character.marth.marth = {
  name: "character.marth.marth",
  shader: "player",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: shockwave.mat */
Asset.prototype.material.character.marth.effect.shockwave = {
  name: "character.marth.effect.shockwave",
  shader: "particle",
  shadow: false,
  texture0: "character/marth/effect/shockwave",
};

/* Source File: shockwaveGround.mat */
Asset.prototype.material.character.marth.effect.shockwaveGround = {
  name: "character.marth.effect.shockwaveGround",
  shader: "effect",
  shadow: false,
  texture0: "character/marth/effect/shockwave",
};

/* Source File: slash.mat */
Asset.prototype.material.character.marth.effect.slash = {
  name: "character.marth.effect.slash",
  shader: "effect_slash",
  shadow: false,
  texture0: "character/marth/effect/slashmask",
  texture1: "character/marth/effect/slashgrad",
};

/* Source File: riposte.mat */
Asset.prototype.material.character.marth.effect.riposte = {
  name: "character.marth.effect.riposte",
  shader: "effect_slash",
  shadow: false,
  texture0: "character/marth/effect/ripostemask",
  texture1: "character/marth/effect/slashgrad",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.captain.ui.iconlarge = {
  name: "character.captain.ui.iconlarge",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/captain/ui/icon_lg",
};

/* Source File: captain.mat */
Asset.prototype.material.character.captain.captain = {
  name: "character.captain.captain",
  shader: "player",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.shiek.ui.iconlarge = {
  name: "character.shiek.ui.iconlarge",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/shiek/ui/icon_lg",
};

/* Source File: shiek.mat */
Asset.prototype.material.character.shiek.shiek = {
  name: "character.shiek.shiek",
  shader: "player",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: shockwave.mat */
Asset.prototype.material.character.shiek.effect.shockwave = {
  name: "character.shiek.effect.shockwave",
  shader: "effect",
  shadow: false,
  texture0: "character/shiek/effect/shockwave",
};

/* Source File: smoke.mat */
Asset.prototype.material.character.shiek.effect.smoke = {
  name: "character.shiek.effect.smoke",
  shader: "particle",
  shadow: false,
  texture0: "character/shiek/effect/smoke",
};

/* Source File: mark.mat */
Asset.prototype.material.character.shiek.effect.mark = {
  name: "character.shiek.effect.mark",
  shader: "effect",
  shadow: false,
  texture0: "character/shiek/effect/mark",
};

/* Source File: flash.mat */
Asset.prototype.material.character.shiek.effect.flash = {
  name: "character.shiek.effect.flash",
  shader: "particle",
  shadow: false,
  texture0: "character/shiek/effect/flash",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.inferno.ui.iconlarge = {
  name: "character.inferno.ui.iconlarge",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/inferno/ui/icon_lg",
};

/* Source File: inferno.mat */
Asset.prototype.material.character.inferno.inferno = {
  name: "character.inferno.inferno",
  shader: "player",
  shadow: true,
  texture0: "character/inferno/inferno",
};

/* Source File: iconlarge.mat */
Asset.prototype.material.character.fox.ui.iconlarge = {
  name: "character.fox.ui.iconlarge",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/fox/ui/icon_lg",
};

/* Source File: blipIcon.mat */
Asset.prototype.material.character.fox.ui.blipIcon = {
  name: "character.fox.ui.blipIcon",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/fox/ui/blip_icon",
};

/* Source File: dashIcon.mat */
Asset.prototype.material.character.fox.ui.dashIcon = {
  name: "character.fox.ui.dashIcon",
  shader: "simpletrans",
  shadow: false,
  texture0: "character/fox/ui/dash_icon",
};

/* Source File: fox.mat */
Asset.prototype.material.character.fox.fox = {
  name: "character.fox.fox",
  shader: "player",
  shadow: true,
  texture0: "multi/default",
};

/* Source File: shockwave.mat */
Asset.prototype.material.character.fox.effect.shockwave = {
  name: "character.fox.effect.shockwave",
  shader: "particle",
  shadow: false,
  texture0: "character/fox/effect/shockwave",
};

/* Source File: speedline.mat */
Asset.prototype.material.character.fox.effect.speedline = {
  name: "character.fox.effect.speedline",
  shader: "particle",
  shadow: false,
  texture0: "character/fox/effect/speedline",
};

/* Source File: blipBright.mat */
Asset.prototype.material.character.fox.effect.blipBright = {
  name: "character.fox.effect.blipBright",
  shader: "particle",
  shadow: false,
  texture0: "character/fox/effect/blip_bright",
};

/* Source File: spark.mat */
Asset.prototype.material.character.fox.effect.spark = {
  name: "character.fox.effect.spark",
  shader: "particle",
  shadow: false,
  texture0: "character/fox/effect/spark",
};

/* Source File: blip.mat */
Asset.prototype.material.character.fox.effect.blip = {
  name: "character.fox.effect.blip",
  shader: "particle",
  shadow: false,
  texture0: "character/fox/effect/blip",
};

/* Source File: sky.mat */
Asset.prototype.material.sky.final.sky = {
  name: "sky.final.sky",
  shader: "final_space",
  shadow: false,
  texture0: "sky/final/space_color",
  texture1: "sky/final/lines",
  texture2: "sky/final/multi_space",
  texture3: "sky/final/twink",
  texture4: "sky/final/multi_difference",
};

/* Source File: grid.mat */
Asset.prototype.material.map.final.grid = {
  name: "map.final.grid",
  shader: "final_grid",
  shadow: false,
  texture0: "map/final/grid",
};

/* Source File: ceiling.mat */
Asset.prototype.material.map.final.ceiling = {
  name: "map.final.ceiling",
  shader: "final",
  shadow: true,
  texture0: "map/final/stage_dark",
  texture1: "map/final/edge_color",
};

/* Source File: floor.mat */
Asset.prototype.material.map.final.floor = {
  name: "map.final.floor",
  shader: "final",
  shadow: true,
  texture0: "map/final/stage",
  texture1: "map/final/edge_color",
};

/* Source File: wall.mat */
Asset.prototype.material.map.final.wall = {
  name: "map.final.wall",
  shader: "final",
  shadow: true,
  texture0: "map/final/stage",
  texture1: "map/final/edge_color",
};

