"use strict";
/* global Asset */

/* This JS file was generated by NoxioAssetConverter */
Asset.prototype.shader = {};

/* Source File: shadowg */
Asset.prototype.shader.shadow = {
  name: "shadow",
  attributes: [
    {type: "vec3", name: "position"},
  ],
  uniforms: [
    {type: "vec3", name: "transform"},
    {type: "mat4", name: "Pmatrix"},
    {type: "mat4", name: "Lmatrix"},
  ],
  vertex: "precision mediump float;\n\nattribute vec3 position;\n\nuniform vec3 transform;\n\nuniform mat4 Pmatrix;\nuniform mat4 Lmatrix;\n\nvarying float vDepth;\n\nvoid main(void) {\n  vec4 cPos = Pmatrix*Lmatrix*vec4((position+transform), 1.0);\n  float zBuf=cPos.z/cPos.w;\n  vDepth=0.5+zBuf*0.5;\n  gl_Position=cPos;\n}\n",
  fragment: "precision mediump float;\n\nvarying float vDepth;\n\nvoid main(void) {\n  gl_FragColor=vec4(vDepth, 0.,0.,1.);\n}\n",
};

/* Source File: defaultg */
Asset.prototype.shader.default = {
  name: "default",
  attributes: [
    {type: "vec3", name: "position"},
    {type: "vec3", name: "texcoord"},
    {type: "vec3", name: "normal"},
  ],
  uniforms: [
    {type: "mat4", name: "Pmatrix"},
    {type: "mat4", name: "Vmatrix"},
    {type: "mat4", name: "Mmatrix"},
    {type: "mat4", name: "Lmatrix"},
    {type: "mat4", name: "PmatrixLight"},
    {type: "vec3", name: "transform"},
    {type: "sampler2D", name: "sampler"},
    {type: "sampler2D", name: "samplerShadowMap"},
    {type: "vec3", name: "sourceDirection"},
  ],
  vertex: "precision mediump float;\n\nattribute vec3 position;\nattribute vec3 texcoord;\nattribute vec3 normal;\n\nuniform mat4 Pmatrix;\nuniform mat4 Vmatrix;\nuniform mat4 Mmatrix;\n\nuniform mat4 Lmatrix;\nuniform mat4 PmatrixLight;\n\nuniform vec3 transform;\n\nvarying vec3 vUV;\nvarying vec3 vNormal;\nvarying vec3 vLightPos;\n\nvoid main(void) {\n  vec4 cPos = vec4(position+transform, 1.0);\n  vec4 lightPos = Lmatrix*cPos;\n\n  lightPos=PmatrixLight*lightPos;\n\n  vec3 lightPosDNC=lightPos.xyz/lightPos.w;\n\n  vLightPos=vec3(0.5,0.5,0.5)+lightPosDNC*0.5;\n  vNormal=normal;\n  vUV=texcoord;\n  gl_Position = Pmatrix*Vmatrix*Mmatrix*cPos;\n}\n",
  fragment: "precision mediump float;\n\nuniform sampler2D sampler;\nuniform sampler2D samplerShadowMap;\n\nvarying vec3 vUV;\nvarying vec3 vNormal;\nvarying vec3 vLightPos;\n\nconst vec3 sourceAmbientColor=vec3(1.0, 1.0, 1.0);\nconst vec3 sourceDiffuseColor=vec3(1.0, 1.0, 1.0);\nuniform vec3 sourceDirection;\n\nconst vec3 matAmbientColor=vec3(0.3, 0.3, 0.3);\nconst vec3 matDiffuseColor=vec3(0.9, 0.9, 0.9);\nconst float matShininess=10.0;\n\nvoid main(void) {\n  vec2 uvShadowMap=vLightPos.xy;\n  vec4 shadowMapColor=texture2D(samplerShadowMap, uvShadowMap);\n  float zShadowMap=shadowMapColor.r;\n  float shadowCoeff=1.0-smoothstep(0.002, 0.003, vLightPos.z-zShadowMap);\n  vec3 color=vec3(texture2D(sampler, vUV.st));\n  vec3 iAmbient=sourceAmbientColor*matAmbientColor;\n  vec3 iDiffuse=sourceDiffuseColor*matDiffuseColor*max(0., dot(vNormal, sourceDirection*-1.0));\n\n  vec3 I=iAmbient+shadowCoeff*iDiffuse;\n  gl_FragColor = vec4(I*color, 1.) + (vec4(vNormal, 1.0)*0.1);\n}\n",
};

