/* == Init == */
CREATE DATABASE 20XX;
USE 20XX;

/* == Wipe == */

DROP TABLE USERS;
DROP TABLE SETTINGS;
DROP TABLE STATS;
DROP TABLE UNLOCKS;
DROP TABLE TRANSACTIONS;

/* == Build ==*/

CREATE TABLE USERS (
 UID  varchar(32) NOT NULL,
 NAME varchar(32) NOT NULL,
 DISPLAY varchar(32) NOT NULL,
 EMAIL varchar(256) NOT NULL,
 HASH    char(60) binary NOT NULL,
 TYPE varchar(5) NOT NULL,
 SUPPORTER bool NOT NULL DEFAULT FALSE,
 CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 LASTLOGIN timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT USERS_UC UNIQUE (UID,NAME)
);

CREATE TABLE SETTINGS (
 UID  varchar(32) NOT NULL,
 UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 /* --Sound Settings-- */
 VOLMASTER decimal(4,3) NOT NULL,
 VOLMUSIC decimal(4,3) NOT NULL,
 VOLVOICE decimal(4,3) NOT NULL,
 VOLANNOUNCER decimal(4,3) NOT NULL,
 VOLUI decimal(4,3) NOT NULL,
 VOLFX decimal(4,3) NOT NULL,
 /* --Graphics Settings-- */
 GFXUPGAME decimal(4,3) NOT NULL,
 GFXUPUI decimal(4,3) NOT NULL,
 GFXUPSKY decimal(4,3) NOT NULL,
 GFXSHADOWSIZE int NOT NULL,
 GFXSAFEMODE bool NOT NULL DEFAULT FALSE,
 /* --Controls-- */
 CONENABLEGAMEPAD bool NOT NULL DEFAULT FALSE,
 CONACTIONA int NOT NULL,
 CONACTIONB int NOT NULL,
 CONJUMP int NOT NULL,
 CONTAUNT int NOT NULL,
 CONTOSS int NOT NULL,
 CONSCOREBOARD int NOT NULL,
 /* --Game-- */
 GAMCOLOR int NOT NULL,
 GAMREDCOLOR int NOT NULL,
 GAMBLUECOLOR int NOT NULL,
 GAMCUSTOMMESSAGEA varchar(64),
 GAMCUSTOMMESSAGEB varchar(64),
 GAMUSECUSTOMSOUND bool NOT NULL DEFAULT FALSE,
 GAMCUSTOMSOUNDFILE varchar(32),
 GAMLAGCOMP int NOT NULL,
 /* --Toggle-- */
 TOGDISABLEALTS bool NOT NULL DEFAULT FALSE,
 TOGDISABLECUSTOMSOUND bool NOT NULL DEFAULT FALSE,
 TOGDISABLECOLOR bool NOT NULL DEFAULT FALSE,
 TOGDISABLELOG bool NOT NULL DEFAULT FALSE,
 TOGDISABLEMETER bool NOT NULL DEFAULT FALSE,
 CONSTRAINT SETTINGS_UC UNIQUE (UID)
);

CREATE TABLE STATS (
 UID     varchar(32) NOT NULL,
 UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 /* --Credits-- */
 CREDITS     int NOT NULL,
 LIFECREDITS int NOT NULL,
 /* --Counts-- */
 KEELL  int NOT NULL, /* KILL is a reserved word so... next best thing */
 DEATH  int NOT NULL,
 GAMEWIN  int NOT NULL,
 GAMELOSE  int NOT NULL,
 BETRAYED  int NOT NULL,
 BETRAYL  int NOT NULL,
 FIRSTBLOOD  int NOT NULL,
 KILLJOY int NOT NULL,
 ENDEDREIGN  int NOT NULL,
 FLAGCAPTURE  int NOT NULL,
 FLAGDEFENSE  int NOT NULL,
 HILLCONTROL  int NOT NULL,
 PERFECT  int NOT NULL,
 HUMILIATION  int NOT NULL,
 /* --Multkills-- */
 MKX02 int NOT NULL,
 MKX03 int NOT NULL,
 MKX04 int NOT NULL,
 MKX05 int NOT NULL,
 MKX06 int NOT NULL,
 MKX07 int NOT NULL,
 MKX08 int NOT NULL,
 MKX09 int NOT NULL,
 MKX10 int NOT NULL,
 MKX11 int NOT NULL,
 MKX12 int NOT NULL,
 MKX13 int NOT NULL,
 MKX14 int NOT NULL,
 MKX15 int NOT NULL,
 MKX16 int NOT NULL,
 MKX17 int NOT NULL,
 MKX18 int NOT NULL,
 MKX19 int NOT NULL,
 MKX20 int NOT NULL,
 /* --Sprees-- */
 KSX05 int NOT NULL,
 KSX10 int NOT NULL,
 KSX15 int NOT NULL,
 KSX20 int NOT NULL,
 KSX25 int NOT NULL,
 KSX30 int NOT NULL,
 /* --Important-- */
 CUMRES int NOT NULL,
 CONSTRAINT STATS_UC UNIQUE (UID)
);

CREATE TABLE UNLOCKS (
 UID  varchar(32) NOT NULL,
 UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 /* --Characters-- */
 CHAR_BOX  bool NOT NULL DEFAULT FALSE,
 CHAR_CRATE bool NOT NULL DEFAULT FALSE,
 CHAR_VOXEL bool NOT NULL DEFAULT FALSE,
 CHAR_CARGO bool NOT NULL DEFAULT FALSE,
 CHAR_BLOCK bool NOT NULL DEFAULT FALSE,
 CHAR_QUAD bool NOT NULL DEFAULT FALSE,
 CHAR_INFERNO bool NOT NULL DEFAULT FALSE,
 /* --Alternates-- */
 ALT_BOXVO bool NOT NULL DEFAULT FALSE,
 ALT_BOXRED bool NOT NULL DEFAULT FALSE,
 ALT_BOXRAINBOW bool NOT NULL DEFAULT FALSE,
 ALT_BOXGOLD bool NOT NULL DEFAULT FALSE,
 ALT_BOXHIT bool NOT NULL DEFAULT FALSE,
 ALT_BOXFOUR bool NOT NULL DEFAULT FALSE,
 ALT_BOXBLOOD bool NOT NULL DEFAULT FALSE,
 ALT_BOXLOOT bool NOT NULL DEFAULT FALSE,
 ALT_CRATEVO bool NOT NULL DEFAULT FALSE,
 ALT_CRATEORANGE bool NOT NULL DEFAULT FALSE,
 ALT_CRATERAINBOW bool NOT NULL DEFAULT FALSE,
 ALT_CRATEGOLD bool NOT NULL DEFAULT FALSE,
 ALT_CRATEFIRE bool NOT NULL DEFAULT FALSE,
 ALT_CRATEBLACK bool NOT NULL DEFAULT FALSE,
 ALT_CRATELOOT bool NOT NULL DEFAULT FALSE,
 ALT_VOXVO bool NOT NULL DEFAULT FALSE,
 ALT_VOXGREEN bool NOT NULL DEFAULT FALSE,
 ALT_VOXRAINBOW bool NOT NULL DEFAULT FALSE,
 ALT_VOXGOLD bool NOT NULL DEFAULT FALSE,
 ALT_VOXBLACK bool NOT NULL DEFAULT FALSE,
 ALT_VOXLOOT bool NOT NULL DEFAULT FALSE,
 ALT_QUADVO bool NOT NULL DEFAULT FALSE,
 ALT_QUADFIRE bool NOT NULL DEFAULT FALSE,
 ALT_QUADLEGEND bool NOT NULL DEFAULT FALSE,
 ALT_QUADRUNE bool NOT NULL DEFAULT FALSE,
 ALT_BLOCKVO bool NOT NULL DEFAULT FALSE,
 ALT_BLOCKROUND bool NOT NULL DEFAULT FALSE,
 ALT_BLOCKWIN bool NOT NULL DEFAULT FALSE,
 ALT_BLOCKFIRE bool NOT NULL DEFAULT FALSE,
 ALT_BLOCKRO bool NOT NULL DEFAULT FALSE,
 ALT_BLOCKLOOT bool NOT NULL DEFAULT FALSE,
 ALT_CARGOVO bool NOT NULL DEFAULT FALSE,
 ALT_CARGOPLUS bool NOT NULL DEFAULT FALSE,
 ALT_CARGOGOLD bool NOT NULL DEFAULT FALSE,
 ALT_CARGOBLACK bool NOT NULL DEFAULT FALSE,
 ALT_CARGOMINE bool NOT NULL DEFAULT FALSE,
 ALT_CARGORETRO bool NOT NULL DEFAULT FALSE,
 /* --Features-- */
 FT_COLOR bool NOT NULL DEFAULT FALSE,
 FT_MESSAGE bool NOT NULL DEFAULT FALSE,
 FT_SOUND bool NOT NULL DEFAULT FALSE,
 CONSTRAINT UNLOCKS_UC UNIQUE (UID)
);

CREATE TABLE TRANSACTIONS (
 TID varchar(32) NOT NULL,
 UID varchar(32) NOT NULL,
 ITEM varchar(4) NOT NULL,
 CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 COMPLETE bool NOT NULL DEFAULT FALSE,
 CONSTRAINT TRANSACTIONS_UC UNIQUE (TID,UID)
);







