/* == Init == */
CREATE DATABASE 20XX;
USE 20XX;

/* == Wipe == */

DROP TABLE USERS;
DROP TABLE SETTINGS;
DROP TABLE STATS;
DROP TABLE UNLOCKS;

/* == Build ==*/

CREATE TABLE USERS (
 UID  varchar(32) NOT NULL,
 NAME varchar(32) NOT NULL,
 DISPLAY varchar(32) NOT NULL,
 EMAIL varchar(256) NOT NULL,
 HASH    char(60) binary NOT NULL,
 PREMIUM bool,
 CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 LASTLOGIN timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT USERS_UC UNIQUE (UID,NAME)
);

CREATE TABLE SETTINGS (
 UID  varchar(32) NOT NULL,
 UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 /* --Sound Settings-- */
 VOLMASTER decimal(4,3) NOT NULL,
 VOLMUSIC decimal(4,3) NOT NULL,
 VOLVOICE decimal(4,3) NOT NULL,
 VOLANNOUNCER decimal(4,3) NOT NULL,
 VOLFX decimal(4,3) NOT NULL,
 /* --Graphics Settings-- */
 GFXUPGAME decimal(4,3) NOT NULL,
 GFXUPUI decimal(4,3) NOT NULL,
 GFXUPSKY decimal(4,3) NOT NULL,
 GFXSHADOWSIZE int NOT NULL,
 GFXSAFEMODE bool,
 /* --Controls-- */
 CONENABLEGAMEPAD bool,
 CONACTIONA int NOT NULL,
 CONACTIONB int NOT NULL,
 CONJUMP int NOT NULL,
 CONTAUNT int NOT NULL,
 CONTOSS int NOT NULL,
 CONSCOREBOARD int NOT NULL,
 /* --Game-- */
 GAMCOLOR int NOT NULL,
 GAMREDCOLOR int NOT NULL,
 GAMBLUECOLOR int NOT NULL,
 GAMUSECUSTOMSOUND bool,
 GAMCUSTOMSOUNDFILE varchar(32),
 /* --Toggle-- */
 TOGDISABLEALTS bool,
 TOGDISABLECUSTOMSOUND bool,
 TOGDISABLECOLOR bool,
 CONSTRAINT SETTINGS_UC UNIQUE (UID)
);

CREATE TABLE STATS (
 UID     varchar(32) NOT NULL,
 UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 /* --Credits-- */
 CREDITS     int NOT NULL,
 LIFECREDITS int NOT NULL,
 /* --Counts-- */
 KEELL  int NOT NULL, /* KILL is a reserved word so... next best thing */
 DEATH  int NOT NULL,
 GAMEWIN  int NOT NULL,
 GAMELOSE  int NOT NULL,
 BETRAYED  int NOT NULL,
 BETRAYL  int NOT NULL,
 FIRSTBLOOD  int NOT NULL,
 KILLJOY int NOT NULL,
 ENDEDREIGN  int NOT NULL,
 FLAGCAPTURE  int NOT NULL,
 FLAGDEFENSE  int NOT NULL,
 HILLCONTROL  int NOT NULL,
 PERFECT  int NOT NULL,
 HUMILIATION  int NOT NULL,
 /* --Multkills-- */
 MKX02 int NOT NULL,
 MKX03 int NOT NULL,
 MKX04 int NOT NULL,
 MKX05 int NOT NULL,
 MKX06 int NOT NULL,
 MKX07 int NOT NULL,
 MKX08 int NOT NULL,
 MKX09 int NOT NULL,
 MKX10 int NOT NULL,
 MKX11 int NOT NULL,
 MKX12 int NOT NULL,
 MKX13 int NOT NULL,
 MKX14 int NOT NULL,
 MKX15 int NOT NULL,
 MKX16 int NOT NULL,
 MKX17 int NOT NULL,
 MKX18 int NOT NULL,
 MKX19 int NOT NULL,
 MKX20 int NOT NULL,
 /* --Sprees-- */
 KSX05 int NOT NULL,
 KSX10 int NOT NULL,
 KSX15 int NOT NULL,
 KSX20 int NOT NULL,
 KSX25 int NOT NULL,
 KSX30 int NOT NULL,
 /* --Important-- */
 CUMRES int NOT NULL,
 CONSTRAINT STATS_UC UNIQUE (UID)
);

CREATE TABLE UNLOCKS (
 UID  varchar(32) NOT NULL,
 UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 /* --Characters-- */
 CHAR_BOX  bool,
 CHAR_CRATE bool,
 CHAR_VOXEL bool,
 CHAR_CARGO bool,
 CHAR_BLOCK bool,
 CHAR_QUAD bool,
 CHAR_INFERNO bool,
 /* --Alternates-- */
 ALT_BOXGOLD bool,
 ALT_BOXRED bool,
 ALT_CRATEORANGE bool,
 ALT_VOXELGREEN bool,
 ALT_QUADFIRE bool,
 ALT_BLOCKROUND bool,
 /* --Features-- */
 FT_COLOR bool,
 FT_SOUND bool,
 CONSTRAINT UNLOCKS_UC UNIQUE (UID)
);







