CREATE DATABASE 20XX;
USE 20XX;

CREATE TABLE USERS (
 UID  varchar(32) NOT NULL,
 NAME varchar(32) NOT NULL,
 DISPLAY varchar(32) NOT NULL,
 EMAIL varchar(256) NOT NULL,
 SALT varchar(32) NOT NULL,
 HASH    varchar(64) NOT NULL,
 PREMIUM bool,
 CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UPDATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT USERS_UC UNIQUE (UID,NAME,SALT)
);

CREATE TABLE STATS (
 UID     varchar(32) NOT NULL,
 CREDITS     int,
 LIFETIME_CREDITS int,
 CONSTRAINT STATS_UC UNIQUE (UID)
);

CREATE TABLE SETTINGS (
 UID  varchar(32) NOT NULL,
 CONSTRAINT SETTINGS_UC UNIQUE (UID)
);

CREATE TABLE UNLOCKS (
 UID  varchar(32) NOT NULL,
 CONSTRAINT UNLOCKS_UC UNIQUE (UID)
);
